### ISSUE TITLE
index error at subpath_info.py

### ISSUE THREAD

**Issue by PhilippMarkolin** [canzarlab/McSplicer#1]
**Description**

Trying to run McSplicer on indexed bam file.
McSplicer produces correct output for some gene_ids, but then encounters and index error at subpath_info.py. 

Using hg38 genome assembly and gencode.v32.annotation.gtf 
Bamfiles were created on the same annotation and indexed with SAMtools. 
The pre-processing steps (exonRefine and sigcount) ran without error.

Here is the command that I ran:

```
Your job looked like:

------------------------------------------------------------
# LSBATCH: User input
python2 ./python_code/McSplicer.py --gtf /cluster/home/maphilip/McSplicer/McSplicer_gencode.v32.annotation.gtf --count_file /cluster/home/maphilip/McSplicer/sigcounted_M3UI6.cnt --out_dir /cluster/home/maphilip/McSplicer/output_test --bootstraps 0 --read_len 100 --prefix test 

------------------------------------------------------------

Exited with exit code 1.

Resource usage summary:

    CPU time :                                   309.16 sec.
    Max Memory :                                 2716 MB
    Average Memory :                             2367.15 MB
    Total Requested Memory :                     30000.00 MB
    Delta Memory :                               27284.00 MB
    Max Swap :                                   -
    Max Processes :                              4
    Max Threads :                                5
    Run time :                                   332 sec.
    Turnaround time :                            322 sec.

The output (if any) follows:

Running McSplicer on gene id ENSG00000242268.3 ...
	Output is written to the folder /cluster/home/maphilip/McSplicer/output_test/ENSG00000242268.3.csv
Running McSplicer on gene id ENSG00000270112.4 ...
	Output is written to the folder /cluster/home/maphilip/McSplicer/output_test/ENSG00000270112.4.csv
Running McSplicer on gene id ENSG00000280143.1 ...
	Output is written to the folder /cluster/home/maphilip/McSplicer/output_test/ENSG00000280143.1.csv
Running McSplicer on gene id ENSG00000146083.12 ...
	Output is written to the folder /cluster/home/maphilip/McSplicer/output_test/ENSG00000146083.12.csv
Running McSplicer on gene id ENSG00000263642.1 ...
No counts are found for gene ENSG00000263642.1 . Continuing with the next gene.
	No counts are found for gene ENSG00000263642.1
Running McSplicer on gene id ENSG00000225275.4 ...
No counts are found for gene ENSG00000225275.4 . Continuing with the next gene.
	No counts are found for gene ENSG00000225275.4
[.....]
	Output is written to the folder /cluster/home/maphilip/McSplicer/output_test/ENSG00000233540.1.csv
Running McSplicer on gene id ENSG00000252650.1 ...
No counts are found for gene ENSG00000252650.1 . Continuing with the next gene.
	No counts are found for gene ENSG00000252650.1
Running McSplicer on gene id ENSG00000258501.1 ...
	Output is written to the folder /cluster/home/maphilip/McSplicer/output_test/ENSG00000258501.1.csv
Running McSplicer on gene id ENSG00000166391.15 ...
	Output is written to the folder /cluster/home/maphilip/McSplicer/output_test/ENSG00000166391.15.csv
Running McSplicer on gene id ENSG00000124615.20 ...
	Output is written to the folder /cluster/home/maphilip/McSplicer/output_test/ENSG00000124615.20.csv
Running McSplicer on gene id ENSG00000232001.2 ...
	Output is written to the folder /cluster/home/maphilip/McSplicer/output_test/ENSG00000232001.2.csv
Running McSplicer on gene id ENSG00000070087.14 ...
	Output is written to the folder /cluster/home/maphilip/McSplicer/output_test/ENSG00000070087.14.csv
Running McSplicer on gene id ENSG00000278616.1 ...
	Output is written to the folder /cluster/home/maphilip/McSplicer/output_test/ENSG00000278616.1.csv
Running McSplicer on gene id ENSG00000080986.13 ...
	Output is written to the folder /cluster/home/maphilip/McSplicer/output_test/ENSG00000080986.13.csv
Running McSplicer on gene id ENSG00000279700.1 ...
	Output is written to the folder /cluster/home/maphilip/McSplicer/output_test/ENSG00000279700.1.csv
Running McSplicer on gene id ENSG00000227959.1 ...
	Output is written to the folder /cluster/home/maphilip/McSplicer/output_test/ENSG00000227959.1.csv
Running McSplicer on gene id ENSG00000153561.13 ...
	Output is written to the folder /cluster/home/maphilip/McSplicer/output_test/ENSG00000153561.13.csv
Running McSplicer on gene id ENSG00000251538.7 ...
Index Error at subpath_info.py
list index out of range
i=48, j=0
Index Error at subpath_info.py
list index out of range
i=48, j=0
Traceback (most recent call last):
  File "./python_code/McSplicer.py", line 571, in <module>
    start_sites_dict, end_sites_dict, p_arr_list, q_arr_list = run_EM_bootstrap(cnt_file, gene_id, no_steps, read_length,gene_datalist,disable_end_sites_computation,add_start_stop_nodes)
  File "./python_code/McSplicer.py", line 362, in run_EM_bootstrap
    if (lp_out[Ism] + ls_in[Ism+1]) == 0:
IndexError: list index out of range
```

**Comment by israa-alqassem** [comment]
Hi Philipp,

Can you send me the signature counts and refined gtf files of the gene ENSG00000251538.7 so I can track this issue?

Thank you

**Comment by PhilippMarkolin** [comment]
I am not sure how to get the signature counts for the specific gene. When inspecting the sigcount file I created for my sample (from the bam file), it's just a long list of numbers with no gene names.

Could you specify exactly what you want me to do?


For the gtf file, I could grep the gene ID and output all lines into a new file (see attachment), because the whole genome file is 1.2 GB and too big to upload.

________________________________
Von: israa-alqassem <notifications@github.com>
Gesendet: Dienstag, 1. September 2020 08:14:15
An: canzarlab/McSplicer
Cc: Markolin Philipp; Author
Betreff: Re: [canzarlab/McSplicer] index error at subpath_info.py (#1)


Hi Philipp,

Can you send me the signature counts and refined gtf files of the gene ENSG00000251538.7 so I can track this issue?

Thank you

**Comment by israa-alqassem** [comment]
You're right, no need to upload the whole genome annotation file. Can you grep the gene ID from the gtf file and copy it here? Then you can run exonRefine like:

./bin/exonRefine  ./gtf/ENSG00000251538.7.gtf  -p ./gtf/ENSG00000251538.7_refined.gtf


To get the signature counts only for that specific gene, can you run sigcount on the refined annotation of the gene ENSG00000251538.7? The counts represent the sub(exon) ids with the total number of reads mapped to them.

sth like this:

./bin/sigcount ./bam/all_reads.bam ./gtf/ENSG00000251538.7_refined.gtf ./signature_counts/ENSG00000251538.7_counts

Thanks for the prompt reply.

**Comment by PhilippMarkolin** [comment]
I attached the refined gtf and sig_count files as .txt here.

[ENSG00000251538.7_refined.gtf.txt](https://github.com/canzarlab/McSplicer/files/5155807/ENSG00000251538.7_refined.gtf.txt)
[ENSG00000251538.7_signature_counts.cnt.txt](https://github.com/canzarlab/McSplicer/files/5155808/ENSG00000251538.7_signature_counts.cnt.txt)

**Comment by israa-alqassem** [comment]
I fixed this bug. Please check and let me know if it doesn't work or if you face other issues with our tool.

Thanks, Philipp.
