### ISSUE TITLE
index error at subpath_info.py

### ISSUE THREAD

**Issue by lunazhaoxxx** [canzarlab/McSplicer#4]
I tried to run McSplicer at the third step (the first and second step ran successfully) with the command: 
`python3 ../python_scripts/McSplicer.py --gtf refined_anno.gtf --count_file xxx.cnt --out_dir test1 --read_len 90 --prefix test1`

The program reported an error in the middle way as follows:
`Running McSplicer on gene id ENSG00000138769.11 ...
	Output is written to the folder test1/chr4/ENSG00000138769.11_test1.csv
Running McSplicer on gene id ENSG00000138757.15 ...
Traceback (most recent call last):
  File "../python_scripts/McSplicer.py", line 585, in <module>
    start_sites_dict, end_sites_dict, p_arr_list, q_arr_list = run_EM_bootstrap(cnt_file, gene_id, no_steps, read_length,gene_datalist,disable_end_sites_computation,add_start_stop_nodes)
  File "../python_scripts/McSplicer.py", line 235, in run_EM_bootstrap
    binary_subpath_list, start_end_nodes_subpath_list = get_binary_and_startend_list_for_all_subpaths(subpath_list)
  File "/mnt/d/nanosplicer/nanosplicer/xinyue/real_data/ground_truth/McSplicer/python_scripts/subpath_info.py", line 226, in get_binary_and_startend_list_for_all_subpaths
    binary_node_list,start_end_node_list = get_subpath_info(subpath)
  File "/mnt/d/nanosplicer/nanosplicer/xinyue/real_data/ground_truth/McSplicer/python_scripts/subpath_info.py", line 216, in get_subpath_info
    return compute_binary_and_startend_list(first_most_start,last_most_end,subpath_loc_list)
  File "/mnt/d/nanosplicer/nanosplicer/xinyue/real_data/ground_truth/McSplicer/python_scripts/subpath_info.py", line 126, in compute_binary_and_startend_list
    cond1 = subpath_loc_list[j] <= loc_list[i]  and  subpath_loc_list[j] > loc_list[i+1]
IndexError: list index out of range`

**Comment by israa-alqassem** [comment]
Hi,

Apparently the problem is with gene id ENSG00000138757.15
Can you upload the refined gtf and counter file for that gene only so I can reproduce and debug the issue?

To get the gtf file for that gene, just use the linux command grep, then run:
/bin/exonRefine ./gtf/ENSG00000138757.15 -p ./gtf/ENSG00000138757.15_refined.gtf  

And to get the read counts for gene id ENSG00000138757.15, you can run a command like:
./bin/sigcount ./bam/all_reads.bam ./gtf/ENSG00000138757.15_refined.gtf   ./signature_counts/ENSG00000138757.15_counts

**Comment by lunazhaoxxx** [comment]
Thanks for your reply, and I have attached two files for 'ENSG00000138757.15' here. (They are converted to txt files so I hope they can work.) 
[ENSG00000138757.15_refined.gtf.txt](https://github.com/canzarlab/McSplicer/files/8369594/ENSG00000138757.15_refined.gtf.txt)
[ENSG00000138757.15.sigcount.cnt.txt](https://github.com/canzarlab/McSplicer/files/8369595/ENSG00000138757.15.sigcount.cnt.txt)

**Comment by israa-alqassem** [comment]
Hi again,

This gene does not have enough overlapping reads to correctly quantify alternative splicing/splice site usage. If this problem occurs often, then I'd suggest you check your sample's sequencing depth/read coverage/gene expression and see if you have enough reads to quantify alternative splicing.

Later, I'll fix the program to output a warning message instead of this runtime error.

Thanks for reporting this issue back to us.
